### ISSUE TITLE
Consider publishing to Maven Central

### ISSUE THREAD

**Issue by dreo** [mtamme/signalr-client#1]
Hi @mtamme, thumbs up for your useful library! 👍  Would you please consider $subj? It would make a life a little bit easier for anyone using it :). 

If there's anything I can help you with regarding this, feel free to let me know.

Thanks and keep up good work!

**Comment by mtamme** [comment]
Hi @dreo, since I don't consider the project to be ready for production it makes no sense for me to publish the artifacts. Sorry for that but it's just a prototype.
I started the project before Java 8 came out, the dependencies are outdated and there is further cleanup and refactoring required.
Cheers, Martin

**Comment by dreo** [comment]
Thanks Martin. My original intention why I wrote you was that - be it production ready or not - your library seems to be _working_ (at least in my use case), unlike the original (and seemingly abandoned)  client from Microsoft. But I also understand your reasons.
